### ISSUE TITLE
Make eventing-controller work when Application CRD is not installed

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/eventing-manager#124]
Currently, the eventing-controller is dependent on Application CRs.

In modularization, Applications CRD may not exists, so we have to make eventing-controller work even when Application CRD is not installed.

> Note: EC code is imported, so the flow needs to be changed in Kyma.

The application is used [here](https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/pkg/application/clean.go).

**Task(s):**
- [x]  Check if we are using the Application CRs in eventing-controller.
   - [x] If not, clean up the Application CRs based logix from eventing-controller.
- [x] Test the eventing-manager must work when Application CRD is not installed on cluster.

**Comment by marcobebway** [comment]
I verified the Eventing manager is working without depending on the existence of the application CRD by the following:

- Deploy Eventing manager.
- Enable NATS, Serverless modules.
- Run the [E2E](https://github.com/kyma-project/eventing-manager/tree/main/hack/e2e) tests.
- Verify with the Eventing tools (validation and loadtest).
