### ISSUE TITLE
[EPIC] Module Post Rollout

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-manager#231]
**Description**

The eventing component of the kyma project needs to be transformed into a kyma module. The initial plan and details are outlined in https://github.tools.sap/skydivingtunas/proposals/tree/main/eventing-modularization. This epic will take the initial plan into reality by managing and tracking the actual action items.

The eventing module will implement ideas described in the backend switching epic: kyma-project/kyma#13800

## Required Actions:
- [x] #277

## Optional Actions:
- [ ] #65
- [ ] #144
- [x] #106
- [ ] #183
- [ ] #32
- [ ] Trigger reconciliation whenever Application CRD is added or removed
- [ ] Emit k8s events for any state changes in conditions of Eventing CR
- [ ] #67
- [ ] #73
- [x] #80
- [ ] (Optional) Use more risk-free logic for updating deployments ([reference](https://github.com/kyma-project/eventing-manager/pull/26#discussion_r1276085209)).

## Bug(s):
- [x] #222 
- [x] #228 

## CI/CD:
```
We decided to implement the tests in golang and not use the javascript fast-integration tests.

**Pipelines:**
We need to test 2 CRs for the 2 different backends. 
- Separate pipelines for the two backends.
   - NATS
   - EventMesh
- Separate pipelines for backend switching tests
- Separate pipelines for Tracing and metrics
```

**Question:** 
- Which version of nats-manager to use? main, latest released from fast/stable channel?

**Actions:**

- [x] #75
- [ ] #130
- [x] #131
- [ ] #278
- [ ] CI pipeline for Tracing and metrics
- [ ] Enable commented [e2e tests](https://github.com/kyma-project/eventing-manager/blob/8e81aae2bdc788ca6ba4a1b4955fd7e0f7a5a0f0/hack/e2e/cleanup/cleanup_test.go#L125) for de-provisioning.
- [ ] Test E2E Backend Switching
- [ ] Run Pipeline Integration Tests with k3d
- [ ] Upload Docker Images for PRs too
- [ ] Don't trigger Eventing Manager build pipeline for E2E sink and tests change on PRs
