### ISSUE TITLE
Create PRs to release channels

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-manager#362]
## Description
Once an OSS release of eventing-manager is done and its tested and ready to be rollout to the fast and regular channel, implement a pipeline which will automatically open a PR to the module-manifests repository with required files/changes.

## Tasks:
- [ ] Github tools token or bot account to access the module-manifests repository.
   - [ ] Contact btp-manager people to figure out how to get this.
- [ ] Check similar [pipeline](https://github.com/kyma-project/btp-manager/blob/main/.github/workflows/promote_to_module-manifests.yaml) in btp-manager.
- [ ] Use github action secrets to store sensitive information.
- [ ] Add a workflow in eventing-manager repository with steps:
   - [ ] Dropdown to get the channel name where to promote the release i.e. fast or regular.
   - [ ] Input field (defaults to 'latest release') to get the release version which needs to be promoted to the channel.
   - [ ] Check the release exists.
   - [ ] Clone the module-manifests repository.
   - [ ] Download the release artifacts and replace/modify the required files to the module-manifests repository. Check this script (check external link) for reference.
   - [ ] Create a PR to module-manifests repository.
   - [ ] In the PR description:
      - [ ] mention the name of the person who triggered the pipeline.
      - [ ] Include reference to the milestone.
      - [ ] Add a to-be-filled template in the description which should be later manually filled before approving the PR. Because if we are releasing a new feature then we need to include `whats new` section.

## Hints
- Use `gh` CLI.

## Acceptance
- [ ] Automatically create PRs to module-manifests repository.
