### ISSUE TITLE
Testing the new image

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-manager#364]
## Description
Once the new image is created, it needs to be tested. The pipeline needs to cover two scenarios: E2E tests of the new image and upgrade test from the old image to the new image.

The backend switching test covers the E2E scenario for both E2E test with NATS and with EventMesh backend. So we do not need separate test cases for these two.

## Prerequisites
- Upgrade test action for NATS Backend to be done: #389 
- Upgrade test action for EventMesh Backend to be done: #390
- Backend switching tests to be done: #131

## Helpful Links
- Reusable action is done in BTP Manager [here](https://github.com/kyma-project/btp-manager/blob/main/.github/workflows/run-e2e-tests-reusable.yaml) and is called [here](https://github.com/kyma-project/btp-manager/blob/d2fb8eb29b1ffd03e005c270490834d214457d4f/.github/workflows/run-e2e-tests.yaml#L4) to be executed on PRs

## ToDo
- [ ] Create GithubAction to be used within the release workflow
- [ ] GithubAction executes all 4 test cases

## Acceptance
- [ ] Execute reusable Upgrade Test with NATS Backend from old to new image
- [ ] Execute reusable Upgrade Test with EventMesh Backend from old to new image
- [ ] Execute reusable backend switching test on new image
