### ISSUE TITLE
Scaffold a new controller using kubebuilder

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#4]
Follow the Kubebuilder documentation to scaffold a new Kubebuilder project.

**Tasks:**
- [ ] Scaffold a new controller project using Kubebuilder with Eventing CRD as mentioned in the proposal.
- [ ] Dummy controller doing nothing.

**Comment by mfaizanse** [comment]
```
kubebuilder init --domain kyma-project.io --repo github.com/kyma-project/eventing-manager
```

**Comment by mfaizanse** [comment]
**Checklist:**
- [ ] Logger init
- [ ] `make test-only`
- [ ] Linting make targets
- [ ] Prow build, lint and unit-test jobs
- [ ] Eventing CRD struct
