### ISSUE TITLE
[EPIC] Removal of Subscription version v1alpha1

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#447]
## Description

as announced 6 months ago we will remove the v1alpha1 version of the subscription CR. This allows us to get rid of all webhook related deployments and code and will support maintainability of the eventing-manager.
 
**Task(s):**
- [x] https://github.com/kyma-project/eventing-manager/issues/442
- [x] https://github.com/kyma-project/eventing-manager/issues/446
- [x] https://github.com/kyma-project/eventing-manager/issues/443
- [x] Release new version
