### ISSUE TITLE
React to NATS+EventMesh backend config modifications on Eventing CR

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#45]
Currently, when an [`Eventing CR spec`](https://github.com/kyma-project/eventing-manager/blob/2582a64c42600ec572bfa85680aa3f032460c12a/api/v1alpha1/eventing_types.go#L77) is created then the NATS/EventMesh subscription-manager object is [initialised and started](https://github.com/kyma-project/eventing-manager/blob/a932a66b9a69918c58f122ccafa013eab3bc41c1/internal/controller/eventing/nats.go#L15) with the configurations from the CR. But if someone later changes the configs in the CR then it will not update it in the subscription-manager object.

**Tasks:**
- [x] Identify if CR spec changed or not.
   - [x] Keep an in-memory hash to identify if spec has changed. The hash should only be based on NATS/EventMesh relevant fields in the spec e.g. backend, logging etc.
   - [x] If the spec changed then change the eventing CR status to `Processing`.
- [x] If changed restart/re-init the NATS/EventMesh subscription-manager object with the new configs.
   - [x] Do not do cleanup when stopping the NATS/EventMesh subscription-manager.
- [x] If changing some config for  NATS/EventMesh causes the subscription manager to start (because on backend we cannot change that config), then discuss with team that should we make that field immutable?

**Acceptance Criteria:**
- [x] Changing the Spec should update the relevant NATS/EventMesh eventing infra.
- [x] Do the implementation in separate PRs for NATS and EventMesh.

**Comment by grischperl** [comment]
Open, until EventMesh PR is merged
