### ISSUE TITLE
Implement a sink in golang for e2e tests

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#77]
example: https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/test/fixtures/commerce-mock/lastorder-function.yaml

**Tasks:**
- [x] Implement a sink
   - [x] Receives an event and saves it in-memory.
   - [x] Exposes an API to check if an event was received or not. (based on event ID).
- [x] Have a github action to build and push docker image. ([Example pipeline](https://github.com/kyma-project/eventing-tools/blob/main/.github/workflows/build.yml)).
