### ISSUE TITLE
Make eventing-publisher-proxy work when Application CRD is not installed

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#94]
Currently, the eventing-publisher-proxy is dependent on Application CRs, because it tries to fetch applications from the cluster to replace event source if an application by the same name exists.

In modularization, Applications CRD may not exists, so we have to make eventing-publisher-proxy work even when Application CRD is not installed.

> Note: EPP code is imported, so the flow needs to be changed in Kyma.

**Task(s):**
- [ ] ~In EPP, check if Application CRD is installed or not.~
  - [ ] ~If not installed, then do not try to fetch application CRs.~
  - [ ] ~If installed, then continue with existing flow.~
- [x] Remove installing `applications.applicationconnector.crd.yaml` as part of `make install` in eventing-manager ([here](https://github.com/kyma-project/eventing-manager/blob/8e81aae2bdc788ca6ba4a1b4955fd7e0f7a5a0f0/config/crd/kustomization.yaml#L7))

**Update:**
- We decided to add a ENV to enable/disable fetching the Application CRs. We will add the logic in eventing-manager to inject the correct value.

**AC(s):**
- [x] eventing-manager should be able to work when Applications CRD is not installed.
