### ISSUE TITLE
Check if APIRule CRD is installed, otherwise stop reconciliation for EventMesh

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/eventing-manager#95]
For eventing-manager to work with EventMesh backend, we need to check if the API-gateway module.

**Task(s):**
- [x] For Eventing CR configured with `EventMesh` backend, check if APIRule CRD is installed.
   - [x] If not installed, then stop reconciliation for the Eventing CR and show a message with relevant information in the Eventing CR.
   - [x] If installed, then continue reconciling.

**Comment by mfaizanse** [comment]
Not needed anymore because of https://github.com/kyma-project/eventing-manager/issues/140
